### ISSUE TITLE
Unable to run orchestrate-pipelines Job 

### ISSUE THREAD

**Issue by johnlonganecker** [pivotalservices/pcf-pipelines-maestro#14]
Using `ccddab2abcc434c831b3ce0816dac3be1037d0a4`

When running `orchestrate-pipelines` job we get this error message.

```
Processing Gated Apply Changes job patch to upgrade-tile pipeline template - removing wait_for_opsman task.
2017/09/26 19:39:49 error applying patch: could not expand pointer: /jobs/name=upgrade-tile/task=wait-opsman-clear
```

When we changed the pcf-pipelines tag from `v0.16.0` to `v0.15.4` we were able to run the `orchestrate-pipelines` job.

**Comment by lsilvapvt** [comment]
Support for pcf-pipelines v0.16.0 added in https://github.com/pivotalservices/pcf-pipelines-maestro/commit/ae49f7154295532ee5bdd88374f4eff796310818 .  Since the OOTB pcf-pipelines now provide a separate Apply-Changes job, the gatedApplyChanges customization flag now only changes the trigger flag to `false` for that job.
