### ISSUE TITLE
Could not reach the Concourse server called main

### ISSUE THREAD

**Issue by keraghu** [pivotalservices/pcf-pipelines-maestro#19]
Hi Team,

I am trying to set up the pipelines for different PCF environments using Maestro, while creating the team am getting error:( see the below error)
      could not reach the Concourse server called main:
      inappropriate ioctl for device

Can you please suggest me how to move forward from here, am i need to do any configuraiton? please suggest

**Comment by lsilvapvt** [comment]
Hi @keraghu . 
I've seen this error when using an old version of Maestro code (prior to v0.1.2) with a new version of Concourse (v3.4.1+, whose `fly` command supports the `non-interactive` mode). What are the versions that you are using?

**Comment by keraghu** [comment]
am using concourse version 3.4.0 ,
Can i upgrade only the fly cli version to 3.4.1, instead of upgrading the complete concourse

**Comment by lsilvapvt** [comment]
Hi @keraghu, that would be a good question for the Concourse team, as I'm not sure if `fly` itself would accept it. Ideally, for you to use the latest version of Maestro, an upgrade of Concourse would be recommended. 
In case you want to try a local patch/code revert until you decide and execute on a Concourse upgrade, this is the Maestro code change to support Concourse 3.4.1+: https://github.com/pivotalservices/pcf-pipelines-maestro/commit/ccddab2abcc434c831b3ce0816dac3be1037d0a4#diff-c7dce6e866276dc01448ad7ad2d231ed . Regards.

**Comment by keraghu** [comment]
Hi 
Thanks for the quick reply,
I have upgraded my concourse to 3.4.1 and fly command, still i am getting the error,
Is there any specific version of fly i need to upgrade ?? can you please suggest

**Comment by lsilvapvt** [comment]
Hi @keraghu, From a Concourse upgrade perspective, their docs recommend upgrading to 3.5.0 instead of 3.4.1 due to issues with 3.4.1. From the Maestro perspective, either one of those Concourse versions should work fine with the latest releases.

So, double check that you have the right parameters configured for your Concourse server (https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/common/credentials.yml#L30) .

The error message you reported `could not reach the Concourse server called main` could be caused by an incorrect Concourse server url in parameter `concourse_url` from `credentials.yml`.

It may also help to debug the problem by inspecting the commands issued by Maestro's scripts: just set `enableDebugMessages` parameter to `true` and re-run Maestro (https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/common/credentials.yml#L92). Regards.

**Comment by keraghu** [comment]
That error is surpassed, now it throwing the below error:
+ ./fly -t LAB-DEV set-pipeline -p LAB-DEV-Upgrades -c ./singleUpgradePipeline.yml -l ./common/credentials.yml -l ./foundations/LAB-DEV.yml -n
could not resolve old-style template vars: yaml: line 149: did not find expected key

**Comment by lsilvapvt** [comment]
Errors of this type (`could not resolve old-style template vars`) are typically caused by missing params expected for a pipeline. Make sure you have all of the required params provided in your credentials.yml and LAB-DEV.yml files.
If you are familiar with Concourse's `fly intercept` command (https://concourse.ci/fly-intercept.html), you could also intercept the container in which the Maestro task ran and then inspect file `pcf-pipelines-maestro/singleUpgradePipeline.yml` to look at which parameter you are  missing in line 149 of that generated yml file.

**Comment by keraghu** [comment]
Hi 
Now we are getting this error, does that mean is it expecting variable tile_upload_timeout  expected ??? 
could not resolve old-style template vars: 1 error occurred:
* unbound variable in template: 'tile_upload_timeout'

**Comment by lsilvapvt** [comment]
@keraghu That is interesting, I don't see a configurable `tile_upload_timeout` param in the `pcf-pipelines` project anymore. It could be that you are pointing to a relatively old version of it.
What is the version of the `pcf-pipelines` that you are pointing to in your config file https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/common/credentials.yml#L65 ?

**Comment by keraghu** [comment]
i have reset up the pcf-pipelines and pcf-pipelines-maestro with the latest versions,
pipeline is trying to insall the fly cli, it is failing at that time, can you suggest ont his.
Proxy request sent, awaiting response... 504 Gateway Timeout
2018-01-24 19:15:43 ERROR 504: Gateway Timeout.

**Comment by keraghu** [comment]
Hi lsilvapvt
I reverted to the older version and and manually removed the 'tile_upload_timeout' attributes and it worked.  Now i am able to run the pipeline successfully.
Thanks for your help.

**Comment by lsilvapvt** [comment]
Hi @keraghu , I'm glad to hear that you got the pipeline to run successfully. Thanks for the update.

**Comment by keraghu** [comment]
Hi lsilvapvt
While connecting to Ops manager, getting the below issue,

could not execute "curl": failed to make api request: failed submitting request: token could not be retrieved from target url: Post https://<<ops.manager.com/uaa/oauth/token: Bad Gateway

Do we need to mention/configure the porxy to resolve the issue ??
Can you please suggest on this.
