### ISSUE TITLE
S3 ssl boolean issue

### ISSUE THREAD

**Issue by mylucidreality** [pivotalservices/pcf-pipelines-maestro#21]
disable_ssl: {{s3-disable-ssl}} need to be changed to disable_ssl: ((s3-disable-ssl))
Otherwise concourse returns an error.

**Comment by lsilvapvt** [comment]
Hello @mylucidreality ,
I think what is causing the problem is an empty value for parameter `s3-disable-ssl` in the `credentials.yml` file: https://github.com/pivotalservices/pcf-pipelines-maestro/blob/master/common/credentials.yml#L73,
Please try to set that parameter to `true` or `false` (depending on whether or not you want to disable ssl verification for your S3 repo) in your copy of `credentials.yml`.
If the problem persists, please let me know which type of IaaS and S3 server you are using it for.
Thanks!
