### ISSUE TITLE
Buildpack ugprade: Incorrect usage: value for POSITION must be integer

### ISSUE THREAD

**Issue by akamalov** [pivotalservices/pcf-pipelines-maestro#34]
**Environment**

```
PCF: 2.0.14
PCF-Pipelines-Release: 0.23.1
Concourse: 3.14.0
```
What would be the regex syntax for the buildpack upgrades? Tried to use 'as-is', but apparently this didn't work:

```
# ********************* Buildpack upgrades - Candidate and Current Buildpack Versions ****
# BoM_bp_go_buildpack_candidate: Go 1.8.1
# BoM_bp_go_buildpack_current: Go 1.8.0
BoM_bp_java_buildpack_candidate: Java Buildpack 3.13
BoM_bp_java_buildpack_current: Java Buildpack 3.12
BoM_bp_java_buildpack_offline_candidate: Java Buildpack 3.13
BoM_bp_java_buildpack_offline_current: Java Buildpack 3.12
# BoM_bp_binary_buildpack_candidate: Binary 1.0.12
# BoM_bp_binary_buildpack_current: Binary 1.0.11
# BoM_bp_dotnet_core_buildpack_candidate: .NET Core 1.0.16
# BoM_bp_dotnet_core_buildpack_current: .NET Core 1.0.15
BoM_bp_nodejs_buildpack_candidate: NodeJS 1.5.34
BoM_bp_nodejs_buildpack_current: NodeJS 1.5.32
# BoM_bp_php_buildpack_candidate: PHP 4.3.31
# BoM_bp_php_buildpack_current: PHP 4.3.30
BoM_bp_python_buildpack_candidate: Python 1.5.18
BoM_bp_python_buildpack_current: Python 1.5.17
BoM_bp_ruby_buildpack_candidate: Ruby 1.6.37
BoM_bp_ruby_buildpack_current: Ruby 1.6.37
```
**Message**
```
Incorrect usage: value for POSITION must be integer
```
**Screenshot**
![image](https://user-images.githubusercontent.com/7885257/42393420-55f9184a-8124-11e8-916e-db25d1cafd44.png)

**Comment by lsilvapvt** [comment]
Thanks for reporting the problem @akamalov .
The root cause of the problem was the fact that PivNet returns multiple files when the corresponding concourse resource retrives releases for the Java buildpack.
To fix it, a globs configuration was added for the Java Buildpack in `common/buildpacks-metadata/globs.yml`. Please update your corresponding file in your maestro repository with that information and it should fix the problem for you.
Also, please note in commit https://github.com/pivotalservices/pcf-pipelines-maestro/commit/19352beaa972e682c2f11e24c6b39293fc3b9399 the version of builpacks in the sample Bill of Materials were updated with the latest ones from PivNet, in case you want to also update that in your foundation config files for your convenience. Regards.

**Comment by akamalov** [comment]
Thank you so much for your reply @lsilvapvt. Once changes applied, I was able to correctly upgrade buildpacks. Thanks so much again.
