### ISSUE TITLE
Implement conditional support for managing upgrade-ops-manager pipeline if iaasType equal to OpenStack

### ISSUE THREAD

**Issue by xyloman** [pivotalservices/pcf-pipelines-maestro#7]
I have been able to successfully implement maestro for AWS but when iaasType is equal to OpenStack we get failures due to no pipeline exists in pcf-pipelines for upgrade-ops-manager.  I have done a hack in some of the sh files to skip managing the ops manager pipeline if iaasType is equal to openstack.  Would a pull request be welcome for the conditional logic or is there a different approach in the works or that might already work.

**Comment by xyloman** [comment]
This would not be necessary if issue: https://github.com/pivotal-cf/pcf-pipelines/issues/124 is implemented.

**Comment by lsilvapvt** [comment]
Hello, the problem with the ops-mgr pipeline failing for OpenStack indeed exists because of the fact that `pcf-pipelines` does not have the corresponding pipeline for that IaaS yet.
In the meantime, in the maestro foundations config file (e.g. ./foundations/NYC-DEV.yml), if you comment out the BoM line for ops-manager, that should avoid the code break until that pipeline is created by `pcf-pipelines`:
```
# BoM_OpsManager_product_version: ...
```

**Comment by xyloman** [comment]
Wow, I should have realized that would have worked that way.  Thanks I will test it out and let you know if I have any other issues.  Thanks.

**Comment by lsilvapvt** [comment]
Closing this issue as the designed workaround for pipelines with no underlying support from pcf-pipelines can simply be commented out from the maestro configuration files.
